---
# Your EKS cluster name (must already exist in AWS)
eks_cluster_name: "eks-dev1"          # e.g. "eks-dev" or "prod-eks"

# Region where the cluster is running
eks_region: "us-east-2"              # e.g. "ap-south-1"

# Target Kubernetes version for control plane
eks_target_version: "1.32"

# New nodegroup we want Ansible to create
new_nodegroup_name: "ng-dev"    # give any name you like

# Nodegroup instance type and sizes
new_nodegroup_instance_type: "t3.medium"
new_nodegroup_min_size: 1
new_nodegroup_desired_size: 2
new_nodegroup_max_size: 3

# IAM role ARN for worker nodes (must exist in your AWS account)
new_node_role_arn: "arn:aws:iam::536346448099:role/eks-nodegroup-role"

# Subnets for the nodegroup (must be in the same VPC as the cluster)
new_nodegroup_subnets:
new_nodegroup_subnets:
  - "subnet-03e9bbc94a833ccbc"
  - "subnet-0c28f125bfc819156"
  - "subnet-04e18635d8c2791b9"
  - "subnet-0f9dfe0eee9ebc82c"
  - "subnet-0a9abd82744f194a1"
  - "subnet-0ecc0011d1c570e48"

